services:
  - type: web
    name: krishva-kitchen-server
    env: docker
    plan: free
    rootDir: Krishva-s-Kitchen
    envVars:
      - key: DB_URL
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: ADMIN_EMAIL
        value: admin@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
